spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    test-on-borrow: true
    validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: password
    init-sql: import.sql
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
logging.level.org.springframework.web: INFO
